### ISSUE TITLE
Cannot find module 'ejs'

### ISSUE THREAD

**Issue by peterbarretto** [ecdeveloper/node-web-crawler#1]
when i run node app and try to access http://localhost:3000/ i get the below error -
     500 Error: Cannot find module 'ejs'

```
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:362:17)
at require (module.js:378:17)
at new View (G:\nodejs\node-web-crawler\node_modules\express\lib\view.js:42:49)
at Function.app.render (G:\nodejs\node-web-crawler\node_modules\express\lib\application.js:486:12)
at ServerResponse.res.render [as partial] (G:\nodejs\node-web-crawler\node_modules\express\lib\response.js:753:7)
at ServerResponse.module.exports.res.render (G:\nodejs\node-web-crawler\node_modules\express-partials\index.js:55:9)
at getHomePage (G:\nodejs\node-web-crawler\routes\index.js:16:6)
at callbacks (G:\nodejs\node-web-crawler\node_modules\express\lib\router\index.js:161:37)
```

**Comment by ecdeveloper** [comment]
Ejs is missing in package.json. Let me fix this .

**Comment by ecdeveloper** [comment]
Get the updates and try running `npm install` once again.

**Comment by peterbarretto** [comment]
I get the below output and error when i try to crawl a site -
  First link in queue: [err/doc] null { __v: 0,
  url: 'example.com',
  depth_level: 0,
  _id: 513032dc0e19799013000001,
  from_redirect: false }
1 Mar 10:17:24 - Start crawling undefined...

G:\nodejs\node-web-crawler\crawling-daemon.js:200
                                if (headers['content-type'].indexOf("text/html")
 != 0) {
                                                            ^
TypeError: Cannot call method 'indexOf' of undefined
    at LinksCheckModel.findOne.doc.remove.urlObj (G:\nodejs\node-web-crawler\cra
wling-daemon.js:200:33)
    at IncomingMessage.<anonymous> (G:\nodejs\node-web-crawler\crawling-daemon.j
s:320:4)
    at IncomingMessage.EventEmitter.emit (events.js:123:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at Socket.socketOnEnd [as onend](http.js:1355:12)
    at TCP.onread (net.js:418:26)

**Comment by ecdeveloper** [comment]
Thank you for reporting. There was an issue with unhandled redirects and empty headers. Fixed.
