### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by DMinerJackie** [ecdeveloper/node-web-crawler#18]
I am going to learn Node.js and Crawling based on your great app, but I find when I set up app.js in Eclipse, it shows error message like:
Express
500 Error: spawn UNKNOWN
at exports._errnoException (util.js:746:11)
at ChildProcess.spawn (child_process.js:1162:11)
at exports.spawn (child_process.js:995:9)
at Object.exports.fork (child_process.js:581:10)
at postAddScraper (C:\Windows\System32\config\systemprofile\git\node-web-crawler\routes\index.js:41:28)
at callbacks (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:161:37)
at param (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:135:11)
at pass (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:170:5)
at Object.router (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:33:10)

Do you know why?
Thanks.

**Comment by ecdeveloper** [comment]
The issue seems to be happening when the main app tries to fork a child process. Looks like it's related to an issue with Eclipse itself. Looks like here is described a similar error - https://groups.google.com/forum/#!topic/nodeclipse/X7gS0mjGjuk

**Comment by DMinerJackie** [comment]
Thanks for your detail answer, I will check it.
