### ISSUE TITLE
The pause and stop button are disabled

### ISSUE THREAD

**Issue by peterbarretto** [ecdeveloper/node-web-crawler#5]
The pause and stop buttons while crawling is going on are disabled. Is the pause and stop feature available?

**Comment by ecdeveloper** [comment]
Not implemented yet. Will add this feature asap.

**Comment by mhhansen** [comment]
Thanks @ecdeveloper for your effort.. this is a great app!

**Comment by ecdeveloper** [comment]
Thank you. Glad you appreciated it :)

**Comment by dmackerman** [comment]
How do I run this thing?

**Comment by DMinerJackie** [comment]
I am going to learn Node.js and Crawling based on your great app, but I find when I set up app.js in Eclipse, it shows error message like:
Express
500 Error: spawn UNKNOWN
at exports._errnoException (util.js:746:11)
at ChildProcess.spawn (child_process.js:1162:11)
at exports.spawn (child_process.js:995:9)
at Object.exports.fork (child_process.js:581:10)
at postAddScraper (C:\Windows\System32\config\systemprofile\git\node-web-crawler\routes\index.js:41:28)
at callbacks (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:161:37)
at param (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:135:11)
at pass (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:142:5)
at Router._dispatch (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:170:5)
at Object.router (C:\Windows\System32\config\systemprofile\git\node-web-crawler\node_modules\express\lib\router\index.js:33:10)

Do you know why?
Thanks.

**Comment by ecdeveloper** [comment]
@DMinerJackie Could you create a separate issue for this?

**Comment by DMinerJackie** [comment]
@ecdeveloper Sure, done
